"""Generate chain-of-thought training data using a local Ollama model.

This module calls `http://localhost:11434/api/chat` with the kimi2.7 cloud
model and asks it to produce short reasoning traces for the same tasks the
agent dataset uses: math, memory lookup, date, web search, and multi-hop
combinations.  The returned CoT can be mixed into the synthetic dataset to
give the small model examples of varied, natural internal monologue.
"""

import json
import urllib.request
import urllib.error
import random
import datetime


OLLAMA_URL = "http://localhost:11434/api/chat"
DEFAULT_MODEL = "kimi2.7-cloud"

# Shared knowledge bases (mirror agent/tools.py and agent_dataset.py).
MEMORY = {
    "project": "newllm",
    "device": "cuda",
    "leader": "grug",
    "tribe": "cavepeople",
    "language": "Python",
    "status": "active",
    "version": "0.1",
}

WEB_KB = {
    "capital of france": "Paris",
    "capital of japan": "Tokyo",
    "capital of germany": "Berlin",
    "president of the united states": "Alice Johnson",
    "current president": "Alice Johnson",
    "prime minister of the uk": "Bob Williams",
    "largest planet": "Jupiter",
    "smallest planet": "Mercury",
    "number of planets": "8",
    "speed of light": "299792458 m/s",
    "boiling point of water": "100 degrees Celsius",
    "freezing point of water": "0 degrees Celsius",
}


def _ask_ollama(prompt: str, model: str = DEFAULT_MODEL, temperature: float = 0.7,
                timeout: float = 60.0) -> str:
    """Send a single chat prompt to Ollama and return the assistant content."""
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "stream": False,
        "options": {"temperature": temperature},
    }
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(OLLAMA_URL, data=data,
                                 headers={"Content-Type": "application/json"},
                                 method="POST")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            result = json.loads(resp.read().decode("utf-8"))
        return result.get("message", {}).get("content", "")
    except urllib.error.URLError as e:
        return f"ERROR: cannot reach Ollama at {OLLAMA_URL}: {e}"
    except json.JSONDecodeError:
        return "ERROR: invalid JSON response from Ollama"


def _math_prompt(rng: random.Random, single_digit: bool = False) -> tuple:
    if single_digit:
        a = rng.randint(0, 9)
        b = rng.randint(1, 9)
    else:
        a = rng.randint(1, 50)
        b = rng.randint(1, 50)
    op = rng.choice(["+", "-", "*"])
    if op == "+":
        ans = a + b
    elif op == "-":
        ans = a - b
    else:
        ans = a * b
    expr = f"{a} {op} {b}"
    question = f"What is {a} {op} {b}?"
    prompt = (
        "You are a helpful assistant that thinks out loud in 1-2 short sentences. "
        f"Question: {question}\n"
        "Explain your reasoning, then give the final answer on its own line as 'Answer: ...'"
    )
    return prompt, str(ans)


def _memory_prompt(rng: random.Random) -> tuple:
    key = rng.choice(list(MEMORY.keys()))
    question = f"What is the {key}?"
    prompt = (
        "You are a helpful assistant that thinks out loud in 1-2 short sentences. "
        f"Question: {question}\n"
        "This value is stored in memory. Explain your reasoning, then give the final answer on its own line as 'Answer: ...'"
    )
    return prompt, str(MEMORY[key])


def _date_prompt() -> tuple:
    now = datetime.datetime.now().isoformat()
    question = "What is the current date and time?"
    prompt = (
        "You are a helpful assistant that thinks out loud in 1-2 short sentences. "
        f"Question: {question}\n"
        "Explain your reasoning, then give the final timestamp on its own line as 'Answer: ...'"
    )
    return prompt, now


def _web_prompt(rng: random.Random) -> tuple:
    key = rng.choice(list(WEB_KB.keys()))
    question = f"What is the {key}?"
    answer = WEB_KB[key]
    prompt = (
        "You are a helpful assistant that thinks out loud in 1-2 short sentences. "
        f"Question: {question}\n"
        "This fact is not in your parametric memory; you would need to search the web. "
        "Explain your reasoning, then give the final answer on its own line as 'Answer: ...'"
    )
    return prompt, answer


def generate_cot_samples(num_samples: int = 100, seed: int = 123,
                         model: str = DEFAULT_MODEL,
                         include_kinds: list = None,
                         single_digit_math: bool = False) -> list:
    """Return list of (question, answer, cot) dicts generated by Ollama.

    If Ollama is not running, the returned CoT strings will be ERROR messages.
    """
    rng = random.Random(seed)
    kinds = include_kinds or ["math", "memory", "date", "web"]
    samples = []
    for i in range(num_samples):
        kind = rng.choice(kinds)
        if kind == "math":
            prompt, answer = _math_prompt(rng, single_digit_math)
        elif kind == "memory":
            prompt, answer = _memory_prompt(rng)
        elif kind == "date":
            prompt, answer = _date_prompt()
        else:
            prompt, answer = _web_prompt(rng)
        cot = _ask_ollama(prompt, model=model)
        samples.append({
            "question": prompt.split("Question: ")[1].split("\n")[0],
            "answer": answer,
            "cot": cot,
            "kind": kind,
            "model": model,
        })
    return samples


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Generate Ollama CoT data for agent training."
    )
    parser.add_argument("--samples", type=int, default=100)
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--seed", type=int, default=123)
    parser.add_argument("--output", default="agent/cot_data.json")
    parser.add_argument("--single-digit-math", action="store_true")
    args = parser.parse_args()

    samples = generate_cot_samples(
        num_samples=args.samples,
        seed=args.seed,
        model=args.model,
        single_digit_math=args.single_digit_math,
    )
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(samples, f, indent=2)
    print(f"wrote {len(samples)} CoT samples to {args.output}")


if __name__ == "__main__":
    main()
